### ISSUE TITLE
override form template

### ISSUE THREAD

**Issue by poznet** [GawainLynch/bolt-extension-boltforms#29]
Lame questrion 
in boltforms.bolt.yml  there are definied form templates , they are located in extensions/vendor ... 

is there any simple way (without edtiting  twig in  extensions/vendor)   to override this  templates  (where to put  my overrided  twigs ?  )

**Comment by GawainLynch** [comment]
Yep… Basically the form name is a relative Twig path, and your template should have higher priority paths than the extension.

As an example, in my theme I create an extension directory and put the form there, and then set those keys in the Bolt Forms config like this:
```yaml
templates:
    form: extensions/boltforms_form.twig
    email: extensions/boltforms_email.twig
    subject: extensions/boltforms_email_subject.twig
```
