### ISSUE TITLE
Runtime error with file upload saving to a contenttype

### ISSUE THREAD

**Issue by DorienD** [GawainLynch/bolt-extension-boltforms#298]
When adding a file upload form field I get a runtime error on submit. The file is uploaded to the directory, the form is not saved to a new item in the contenttype participants.

## Error

```Uncaught Exception: RuntimeError .
RuntimeError in Template.php line 230:
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'INSERT INTO bolt_participants (slug, datecreated, datechanged, datepublish, datedepublish, ownerid, status, templatefields, title_act, first_name, sur_name, address_street, address_zipcode, address_city, telephone, email, link_track, website, twitter, facebook, instagram, upload_bio, upload_photo) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["slug-af80adb67f27602ca034ea33c971410f", "2020-01-06 11:10:25", "2020-01-06 11:10:25", null, null, null, "draft", "[]", "naam act", "Bluup", "Achternaam", "adres", "postcode", "woonplaats", "telefoon", "dorien+2@driebit.nl", "link naar track", "website", "twitter", "facebook", "instagram", {"file":"Users\/dorien\/Projects\/bolt\/groteprijsnl\/\/deepadaptation.1065829b34df099f55d9dfd0.pdf","filename":"Users\/dorien\/Projects\/bolt\/groteprijsnl\/\/deepadaptation.1065829b34df099f55d9dfd0.pdf","title":"deepadaptation.1065829b34df099f55d9dfd0.pdf","basepath":"public\/files\/uploads"}, {"file":"Users\/dorien\/Projects\/bolt\/groteprijsnl\/\/cat-knudu.92638fa91ec706789471c31f.jpeg","filename":"Users\/dorien\/Projects\/bolt\/groteprijsnl\/\/cat-knudu.92638fa91ec706789471c31f.jpeg","title":"cat-knudu.92638fa91ec706789471c31f.jpeg","basepath":"public\/files\/uploads"}]:

Notice: Array to string conversion") in "index.twig" at line 11.
```

## boltforms.bolt.yml:

Form settings:

```
participants:
    database:
        contenttype:
            name: participants                 
            fieldmap:
                title_act: 'title'
                first_name: 'first_name'
                sur_name: 'sur_name'
                address_street: 'address_street'
                address_zipcode: 'address_zipcode'
                address_city: 'address_city'
                telephone: 'telephone'
                email: 'email'
                link_track: 'link_track'
                website: 'website'
                twitter: 'twitter'
                facebook: 'facebook'
                instagram: 'instagram'
                upload_bio: 'upload_bio'
                upload_photo: 'upload_photo'
    fields:
        first_name:
            type: text
            options:
                required: true
                label: "Voornaam"
        sur_name:
            type: text
            options:
                required: true
                label: "Achternaam"
        title_act:
            type: text
            options:
                label: "Naam Act"
        address_street:
            type: text
            options:
                required: true
                label: "Adres"
        address_zipcode:
            type: text
            options:
                required: true
                label: "Postcode"
        address_city:
            type: text
            options:
                required: true
                label: "Woonplaats"
        telephone:
            type: text
            options:
                required: true
                label: "Telefoonnummer"
        email:
            type: email
            options:
                required: true
                label: "Email contactpersoon"
        link_track:
            type: text
            options:
                required: true
                label: "Link naar track"
        website:
            type: text
            options:
                required: true
                label: "Website"
        twitter:
            type: text
            options:
                required: true
                label: "twitter"
        facebook:
            type: text
            options:
                required: true
                label: "Facebook"
        instagram:
            type: text
            options:
                required: true
                label: "Instagram"
        upload_bio:
            type: file
            options:
                required: false
                label: Biografie (uploaden)
        upload_photo:
            type: file
            options:
                required: false
                label: Foto (uploaden)
        submit:
            type: submit
            options:
                label: Verstuur
                attr:
                    class: button primary
        status: 
            type: hidden
            options:
                label: false
                attr:
                    value: draft
```
Upload settings:

```
uploads:
   enabled: true                                  
   base_directory: public/files/uploads           
   filename_handling: prefix                      
   management_controller: false
```

## Contenttype

```
participants:
    name: Participants
    singular_name: Participant
    fields:
        title_act:
            type: text
            class: large
            group: content
        first_name:
            type: text
        sur_name:
            type: text
        address_street:
            type: text
        address_zipcode:
            type: text
        address_city:
            type: text
        telephone:
            type: text
        email:
            type: text
        link_track:
            type: text
        website:
            type: text
        twitter:
            type: text
        facebook:
            type: text
        instagram:
            type: text
        upload_bio:
            type: file
        upload_photo:
            type: file
    default_status: draft
    recordsperpage: 20
```
