### ISSUE TITLE
Individual form templates aren't used

### ISSUE THREAD

**Issue by marck-consulting** [GawainLynch/bolt-extension-boltforms#307]
If bolt-boltforms.yaml template block is configured as:
```
templates:
    form: 'extensions/boltforms/form.html.twig'
    email: 'extensions/boltforms/email.html.twig'
    subject: 'extensions/boltforms/subject.html.twig'
    files: 'extensions/boltforms/file_browser.twig'
```

and a form is configured as:
```
## Subscribe
subscribe:
    templates:
        form: 'partials/_subscribe.twig'
    feedback:
        success: Deine E-Mail Adresse email wurden erfolgreich eingetragen.
        error: Die eingegebene E-Mail Adresse ist ungültig.
    fields:
        email:
            type: email
            options:
                required: true
                label: E-Mail Adresse
                attr:
                    placeholder: E-Mail Adresse
                constraints: [ NotBlank, Email ]
        submit:
            type: submit
            options:
                label: Submit
                attr:
                    class: button primary
```
The used template is still "form.html.twig" when it should be "_subscribe.twig" instead.
