### ISSUE TITLE
from_email not substituted from filed

### ISSUE THREAD

**Issue by kaolpr** [GawainLynch/bolt-extension-boltforms#309]
I have the following configuration in my form configuration:

```yaml
from_name: name
from_email: email_address
```

I expect `from_name` and `from_email` to be substituted with value from `name` and `email_address` fields defined for the form:

```yaml
fields:
        name:
            type: text
            options:
                required: true
                label: Name and surname
                attr:
                    placeholder: Place your name here...
                constraints: [ NotBlank ]

        email_address:
            type: email
            options:
                required: true
                label: E-mail address
                attr:
                    placeholder: Your e-mail address
                constraints: [ NotBlank, Email ]
```

However, it seems not to happen as on submission I'm receiving 500 error: `An exception has been thrown during the rendering of a template ("Email "email_address" does not comply with addr-spec of RFC 2822.").` It looks that `email_address` is treated as a string literal rather than field name.

```
bolt/core                                      4.2.2     🧿 Bolt 4 Core
bolt/forms                                     1.4.7     📦 This Bolt extension can be used to handle forms in your Bolt 4 project.
```
