### ISSUE TITLE
Change value / text of submit button

### ISSUE THREAD

**Issue by melcarthus** [GawainLynch/bolt-extension-boltforms#35]
Hi,

Perhaps it is painstakingly obvious but I cannot find anywhere in the documentation where it states how to change the button text from the standard text submit.

In the extension simpleforms it's button_text: Send it!
But I don't want to use 2 form extensions just because I can't find how boltforms does this :blush:

**Comment by GawainLynch** [comment]
Ah… some things I didn't overly document as BoltForms is just implementing Symfony Forms for Bolt, so their documentation is canonical.

That said, I haven't personally done it (and have servers in bits right now), but it *should* be a simple as:
```yaml
    submit:
      type: submit
      label: Send more beer!
```

The forms are probably the worst documented part of Symfony and I really should find time to improve BoltForms to compensate, but what they do have is [here](http://symfony.com/doc/current/reference/forms/types.html)… But always feel free to ask, I can try to answer :grin:

**Comment by melcarthus** [comment]
label: was the first thing I tried. It does nothing atm.

**Comment by melcarthus** [comment]
Actually nothing works, I don't know if this is possible and all but I also tries, class so I can give it a bootstrap class for a btn e.a. btn btn-succes

**Comment by GawainLynch** [comment]
I can't YAML… It needs to be under the `option:` key like so:

```yaml
    submit:
      type: submit
      options:
          label: Send more beer!
```

As for the class… Yeah, that one is weird! I think there might be a bug in the forms library itself. I am messing around to see if I can find a workaround.

**Comment by GawainLynch** [comment]
Update that… Apparently I suck at YAML… This works for the class as well :+1: 

```yaml
    submit:
      type: submit
      options:
          label: Send more beer!
          attr:
              class: beer
```
