### ISSUE TITLE
Database Insertion issue

### ISSUE THREAD

**Issue by TheTemportalist** [GawainLynch/bolt-extension-boltforms#4]
When inserting from a multi-choice field to a database, the string 'Array' is set, instead of an value actually signifying the options.
Field:
```yaml
mods:
      type: choice
      options:
        required: true
        label: What do you want to subscribe to?
        choices: [ Origin, Compression ]
        multiple: true
```
Database column is named 'mods', type: varchar(256), utf8_general_ci
