### ISSUE TITLE
filtered choice fields

### ISSUE THREAD

**Issue by jadwigo** [GawainLynch/bolt-extension-boltforms#46]
It would be cool to be able to filter the content type results

```yml
  fields:
    lookup:
      type: choice
      options:
        choices: 'contenttype::pages::title::slug'
        filters: 
          firstfilter:
            field: some_property
            value: '>12' # some property is larger than 12
          secondfilter:
            field: another_property
            value: 12 # another property is equal to 12
```

**Comment by GawainLynch** [comment]
This is already doable with constraints:

```yaml
  fields:
    name:
      type: text
      options:
        constraints: [ {Length: {'min': 3, 'max': '32'}} ]
```
