### ISSUE TITLE
ordered choice fields

### ISSUE THREAD

**Issue by jadwigo** [GawainLynch/bolt-extension-boltforms#47]
It would be cool to be able sort the content type results on some field

```yml
  fields:
    lookup:
      type: choice
      options:
        choices: 'contenttype::pages::title::slug'
        sort: 'contenttype::pages::-id'
```
or something like

```yml
  fields:
    lookup:
      type: choice
      options:
        choices: 'contenttype::pages::title::slug'
        sort: -publishdate
```
